// Minimal i18n for UI chrome only. Data (bill titles, findings, statuses)
// always stays German — intentional, matching the reference site.
import { createContext, useContext } from "react";

export type Lang = "de" | "en";

export type StringKey =
  | "subtitle"
  | "navBills"
  | "navAbout"
  | "riskHigh"
  | "riskMedium"
  | "riskLow"
  | "riskUnknown"
  | "allStatuses"
  | "searchPlaceholder"
  | "colNumber"
  | "colTitle"
  | "colStatus"
  | "colFindings"
  | "colUpdated"
  | "prev"
  | "next"
  | "rangeOf"
  | "emptyState"
  | "loading"
  | "errorGeneric"
  | "notFoundTitle"
  | "notFoundBody"
  | "backToList"
  | "pdfLink"
  | "initiator"
  | "status"
  | "date"
  | "severityHeading"
  | "worstFinding"
  | "summaryHeading"
  | "findingsHeading"
  | "noFindings"
  | "methodHeading"
  | "methodPromptVersion"
  | "methodModel"
  | "methodAnalyzedAt"
  | "methodDocuments"
  | "methodDocumentsAmended"
  | "docTypeGesetzentwurf"
  | "docTypeBeschlussempfehlung"
  | "relatedNotAnalyzed"
  | "disclaimer"
  | "footer"
  | "evalLink"
  | "evalTitle"
  | "evalReports"
  | "evalNoReports";

const de: Record<StringKey, string> = {
  subtitle: "KI-Analyse von Gesetzentwürfen des Deutschen Bundestags",
  navBills: "Gesetzentwürfe",
  navAbout: "Info",
  riskHigh: "Hoch",
  riskMedium: "Mittel",
  riskLow: "Niedrig",
  riskUnknown: "Unanalysiert",
  allStatuses: "Alle Status",
  searchPlaceholder: "Titel durchsuchen …",
  colNumber: "Nummer",
  colTitle: "Titel",
  colStatus: "Status",
  colFindings: "Befunde",
  colUpdated: "Aktualisiert",
  prev: "Zurück",
  next: "Weiter",
  rangeOf: "von",
  emptyState: "Noch keine Analysen — Pipeline ausführen.",
  loading: "Wird geladen …",
  errorGeneric: "Fehler beim Laden der Daten.",
  notFoundTitle: "Gesetzentwurf nicht gefunden",
  notFoundBody: "Dieser Gesetzentwurf existiert nicht oder wurde entfernt.",
  backToList: "Zurück zur Übersicht",
  pdfLink: "Drucksache als PDF",
  initiator: "Urheber",
  status: "Status",
  date: "Datum",
  severityHeading: "Schweregrad",
  worstFinding: "Schwerster Befund",
  summaryHeading: "Gesamteinschätzung",
  findingsHeading: "Befunde",
  noFindings: "Keine konkreten Befunde.",
  methodHeading: "Methodik",
  methodPromptVersion: "Prompt-Version",
  methodModel: "Modell",
  methodAnalyzedAt: "Analysiert am",
  methodDocuments: "Analysierte Dokumente",
  methodDocumentsAmended:
    "Die Befunde beziehen sich auf den Entwurf in der Fassung der Beschlussempfehlung.",
  docTypeGesetzentwurf: "Gesetzentwurf",
  docTypeBeschlussempfehlung: "Beschlussempfehlung",
  relatedNotAnalyzed: "in der Analyse nicht berücksichtigt",
  disclaimer:
    "Die Befunde stammen von einem Sprachmodell. Sie sind ungeprüft und können falsch oder unvollständig sein. Dies ist ein Experiment im maschinellen Lesen: keine Autorität, keine Rechtsberatung und keine politische Empfehlung.",
  footer:
    "Datenquelle: Deutscher Bundestag – DIP · Kein offizielles Angebot des Bundestags",
  evalLink: "Evaluation",
  evalTitle: "Evaluation des Analyseprompts",
  evalReports: "Berichte",
  evalNoReports: "Noch keine Berichte veröffentlicht.",
};

const en: Record<StringKey, string> = {
  subtitle: "AI analysis of German Bundestag draft bills",
  navBills: "Draft bills",
  navAbout: "About",
  riskHigh: "High",
  riskMedium: "Medium",
  riskLow: "Low",
  riskUnknown: "Not analyzed",
  allStatuses: "All statuses",
  searchPlaceholder: "Search titles …",
  colNumber: "Number",
  colTitle: "Title",
  colStatus: "Status",
  colFindings: "Findings",
  colUpdated: "Updated",
  prev: "Back",
  next: "Next",
  rangeOf: "of",
  emptyState: "No analyses yet — run the pipeline.",
  loading: "Loading …",
  errorGeneric: "Failed to load data.",
  notFoundTitle: "Draft bill not found",
  notFoundBody: "This draft bill does not exist or was removed.",
  backToList: "Back to overview",
  pdfLink: "Drucksache as PDF",
  initiator: "Initiator",
  status: "Status",
  date: "Date",
  severityHeading: "Severity",
  worstFinding: "Worst finding",
  summaryHeading: "Overall assessment",
  findingsHeading: "Findings",
  noFindings: "No concrete findings.",
  methodHeading: "Methodology",
  methodPromptVersion: "Prompt version",
  methodModel: "Model",
  methodAnalyzedAt: "Analyzed at",
  methodDocuments: "Analyzed documents",
  methodDocumentsAmended:
    "Findings refer to the draft as amended by the committee recommendation.",
  docTypeGesetzentwurf: "Draft bill",
  docTypeBeschlussempfehlung: "Committee recommendation",
  relatedNotAnalyzed: "not used in the analysis",
  disclaimer:
    "The findings are generated by a language model. They are unreviewed and may be wrong or incomplete. This is an experiment in machine reading: not an authority, and not legal advice or a political recommendation.",
  footer:
    "Data source: Deutscher Bundestag – DIP · Not an official Bundestag service",
  evalLink: "Evaluation",
  evalTitle: "Evaluation of the analysis prompt",
  evalReports: "Reports",
  evalNoReports: "No reports published yet.",
};

export const DICTS: Record<Lang, Record<StringKey, string>> = { de, en };

export const STORAGE_KEY = "llm-lesung.lang";

export function loadLang(): Lang {
  try {
    const v = localStorage.getItem(STORAGE_KEY);
    if (v === "de" || v === "en") return v;
  } catch {
    // ignore (e.g. storage disabled)
  }
  return "de";
}

export function saveLang(lang: Lang): void {
  try {
    localStorage.setItem(STORAGE_KEY, lang);
  } catch {
    // ignore
  }
}

export interface I18nContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: StringKey) => string;
}

export const I18nContext = createContext<I18nContextValue | null>(null);

export function useI18n(): I18nContextValue {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be used within I18nProvider");
  return ctx;
}
